version: "3.1"

services:
    lotus-dev:
        container_name: lotus
        image: lotus-dev
        user: root
        network_mode: host
        privileged: true
        environment: 
            - LOTUS_PATH=/root/devnet/.lotusDevnet
            - LOTUS_MINER_PATH=/root/devnet/.lotusminerDevnet
            - LOTUS_SKIP_GENESIS_CHECK=_yes_
            - LOTUS_MINER_JOB_LOG_PATH=/root
        command: > 
            bash -c "lotus fetch-params 2048 &&
            lotus-seed pre-seal --sector-size 2KiB --num-sectors 2 &&
            lotus-seed genesis new /root/localnet.json &&
            lotus-seed genesis add-miner /root/localnet.json /root/.genesis-sectors/pre-seal-t01000.json &&
            nohup lotus daemon --lotus-make-genesis=/root/devgen.car --genesis-template=/root/localnet.json --bootstrap=false >/root/lotus-daemon.log 2>&1 & sleep 20 &&
            lotus wallet import --as-default /root/.genesis-sectors/pre-seal-t01000.key &&
            lotus-miner init --no-local-storage --genesis-miner --actor=t01000 --sector-size=2KiB --pre-sealed-sectors=/root/.genesis-sectors --pre-sealed-metadata=/root/.genesis-sectors/pre-seal-t01000.json --nosync &&
            nohup lotus-miner run --nosync > /root/lotus-miner.log 2>&1
            "
        volumes: 
            - storage1:/root/devnet/storage1
            - storage2:/root/devenet/storage2
        tty: true
        stdin_open: true

volumes: 
    storage1:
    storage2:

        